/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useEffect } from 'react'
import { useGLTF, Html } from '@react-three/drei'
import * as THREE from 'three'
import { useRobot } from './RobotContext'

export function Model(props: { isSpeaking: boolean } & JSX.IntrinsicElements['group']) {
  const { nodes } = useGLTF('/models/robot.glb')
  const { appearance } = useRobot()
  const [mouthImage, setMouthImage] = useState('/images/mouthCloseHappy.png')
  const [eyeImage, setEyeImage] = useState('/images/neutralOpenEyes.png')

  const hat = useGLTF('/models/hat.glb')

  useEffect(() => {
    if (props.isSpeaking) {
      const interval = setInterval(() => {
        setMouthImage((prev) =>
          prev === '/images/mouthCloseHappy.png'
            ? '/images/mouthOpenHappy.png'
            : '/images/mouthCloseHappy.png'
        )
      }, 100) // Toggles every 0.1 seconds
      return () => clearInterval(interval)
    } else {
      setMouthImage('/images/mouthCloseHappy.png')
    }
  }, [props.isSpeaking])

  useEffect(() => {
    const blinkInterval = setInterval(() => {
      setEyeImage('/images/neutralCloseEyes.png')
      setTimeout(() => {
        setEyeImage('/images/neutralOpenEyes.png')
      }, 200) // How long the eyes stay closed
    }, 4000) // Blink every 4 seconds

    return () => clearInterval(blinkInterval)
  }, [])

  const mesh = nodes.geometry_0 as THREE.Mesh
  const robotColor = new THREE.Color(appearance.bodyColor).convertSRGBToLinear()

  return (
    <group {...props} dispose={null} scale={5} position={[0, 0, 0]}> 
      <mesh
        castShadow
        receiveShadow
        geometry={mesh.geometry}
        material={mesh.material}
      >
        <meshStandardMaterial color={robotColor} />
      </mesh>
      {appearance.hasHat && (
        <primitive object={hat.scene} position={[0, 0, 0]} rotation={[0, 0, 0]} />
      )}
      <Html position={[0, 0.15, 0.2]} transform>
      <img src={mouthImage} alt="mouth" width="10" />
      </Html>
      <Html position={[0, 0.3, 0.2]} transform>
        <img src={eyeImage} alt="eyes" width="10" />
      </Html>
    </group>
  )
}

useGLTF.preload('/models/robot.glb')
useGLTF.preload('/models/hat.glb')
