/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('models/robot.glb')
  const mesh = nodes.geometry_0 as THREE.Mesh

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={mesh.geometry}
        //material={materials['Material.001']}
      >
        <meshStandardMaterial color="pink" />
     </mesh>
    </group>
  )
}

useGLTF.preload('/robot.glb')
